---
- name: Install and start Apache HTTPD
  hosts: all
  vars:
    index_message: "This is your new apache server"
    index_image: ""

  tasks:
    - name: httpd package is present
      uri:
        url: "{{ ansible_hostname }}"
        method: GET
        return_content: yes
      register: index

    - name: httpd is started
      service:
        name: httpd
        state: restarted
        enabled: true
