---
- name: Install and start Apache HTTPD
  hosts: all
  vars:
    index_message: "This is your new apache server"
    index_image: ""

  tasks:
    - name: retrieve information from host 
      uri: 
        url: "https://{{ ansible_host }}:80"
        method: GET
        return_content: yes
        validate_certs: no
      register: index

    - name: httpd is started
      service:
        name: httpd
        state: restarted
        enabled: true
