---
- name: Checks http connectivity to hosts
  hosts: all
  vars:
    index_message: "This is your new apache server"
    index_imag: ""

  tasks:
    - name: retrieve information from host 
      uri: 
        url: "http://{{ service_public_ip }}:{{ service_port }}"
        validate_certs: no

