- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  tasks:

  - name: ADD VIRTUAL SERVER
    bigip_virtual_server:
      server: "{{private_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: "8443"
      name: "{{ service_vip }}"
      destination: "{{private_ip}}"
      port: "{{ service_port }}"
      enabled_vlans: "all"
#      all_profiles: ['http','cliientssl','oneconnect']
      all_profiles: ['http','oneconnect']
      pool: "{{ service_pool }}"
      snat: "Automap"
      validate_certs: "no"
